apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: exxjv3mxv-dotnet-basic
  janus-idp.io/tekton: exxjv3mxv-dotnet-basic
  backstage.io/kubernetes-id: exxjv3mxv-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: exxjv3mxv-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
