apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: exxjv3mxv-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/exxjv3mxv-dotnet-basic-gitops